FROM node:latest

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_SECRET_VARIABLE
ARG NEXT_PUBLIC_SECRET_VARIABLE2

ENV NEXT_PUBLIC_SECRET_VARIABLE=$NEXT_PUBLIC_SECRET_VARIABLE
ENV NEXT_PUBLIC_SECRET_VARIABLE2=$NEXT_PUBLIC_SECRET_VARIABLE2

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]