version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SECRET_VARIABLE: ${NEXT_PUBLIC_SECRET_VARIABLE}
        NEXT_PUBLIC_SECRET_VARIABLE2: ${NEXT_PUBLIC_SECRET_VARIABLE2}
    image: "europe-north1-docker.pkg.dev/${PROJECT_ID}/docker-test/frontend:latest"
  
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SECRET_VARIABLE: ${NEXT_PUBLIC_SECRET_VARIABLE}
        NEXT_PUBLIC_SECRET_VARIABLE2: ${NEXT_PUBLIC_SECRET_VARIABLE2}
      image: "europe-north1-docker.pkg.dev/${PROJECT_ID}/docker-test/admin:latest"