name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
       PROJECT_ID: ${{ secrets.PROJECT_ID }}
    steps:

      - name: checkout code
        uses: actions/checkout@v2
    
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
    
      - name: build and push the docker image
        run: |
          gcloud auth configure-docker europe-north1-docker.pkg.dev
          docker build \
            --build-arg NEXT_PUBLIC_SECRET_VALUE=${{ secrets.NEXT_PUBLIC_SECRET_VALUE }} \
            -t europe-north1-docker.pkg.dev/$PROJECT_ID/docker-test/app-test:latest .
          docker push europe-north1-docker.pkg.dev/$PROJECT_ID/docker-test/app-test:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy app-test-service \
            --image europe-north1-docker.pkg.dev/$PROJECT_ID/docker-test/app-test:latest \
            --platform managed \
            --region europe-north1 \
            --allow-unauthenticated